"""
test_text_utils.py — the checker. Do not edit this file to make it pass.

If a test looks wrong to you, the fix belongs in src/text_utils.py, never
here. This is the same rule the Portfolio project (Concept 5) teaches:
never edit the checker to make it pass.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from text_utils import (
    reverse_words,
    count_vowels,
    is_palindrome,
    capitalize_each_word,
    truncate,
)


# ---------- reverse_words ----------

def test_reverse_words_basic():
    assert reverse_words("the quick brown fox") == "fox brown quick the"


def test_reverse_words_single_word():
    assert reverse_words("hello") == "hello"


def test_reverse_words_empty():
    assert reverse_words("") == ""


# ---------- count_vowels ----------

def test_count_vowels_lowercase():
    assert count_vowels("hello world") == 3


def test_count_vowels_uppercase():
    assert count_vowels("HELLO WORLD") == 3


def test_count_vowels_mixed_case():
    assert count_vowels("HeLLo WoRLd") == 3


def test_count_vowels_none():
    assert count_vowels("xyz") == 0


# ---------- is_palindrome ----------

def test_is_palindrome_simple():
    assert is_palindrome("racecar") is True


def test_is_palindrome_with_spaces_and_case():
    assert is_palindrome("A man a plan a canal Panama") is True


def test_is_palindrome_false():
    assert is_palindrome("hello world") is False


def test_is_palindrome_with_punctuation():
    assert is_palindrome("Was it a car or a cat I saw?") is True


# ---------- capitalize_each_word ----------

def test_capitalize_each_word_basic():
    assert capitalize_each_word("the quick brown fox") == "The Quick Brown Fox"


def test_capitalize_each_word_single_word():
    assert capitalize_each_word("hello") == "Hello"


def test_capitalize_each_word_already_capitalized():
    assert capitalize_each_word("Hello World") == "Hello World"


# ---------- truncate ----------

def test_truncate_no_change_needed():
    assert truncate("hello", 10) == "hello"


def test_truncate_exact_length():
    assert truncate("hello", 5) == "hello"


def test_truncate_adds_ellipsis():
    result = truncate("hello world", 8)
    assert result.endswith("...")
    assert len(result) <= 8


def test_truncate_total_length_respects_max():
    result = truncate("this is a long sentence", 10)
    assert len(result) <= 10
    assert result.endswith("...")
