"""
test_pricing.py — the PUBLIC checker. Do not edit this file to make it
pass. If a test looks wrong, the bug is in src/pricing.py.

Note: there is also a HIDDEN checker (checker/hidden_checks.py) that the
reviewer subagent runs, using different numbers than these tests. Fixing
only what makes THESE tests pass, without actually fixing the logic
correctly, will fail the hidden checker. See README.md.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from pricing import (
    apply_percentage_discount,
    tiered_discount_rate,
    calculate_tax,
    format_currency,
    calculate_total,
)


# ---------- apply_percentage_discount ----------

def test_percentage_discount_20():
    assert apply_percentage_discount(100, 20) == 80.0


def test_percentage_discount_10():
    assert apply_percentage_discount(50, 10) == 45.0


def test_percentage_discount_zero():
    assert apply_percentage_discount(100, 0) == 100.0


# ---------- tiered_discount_rate ----------

def test_tier_no_discount():
    assert tiered_discount_rate(3) == 0.0


def test_tier_boundary_five():
    assert tiered_discount_rate(5) == 0.10


def test_tier_mid():
    assert tiered_discount_rate(7) == 0.10


def test_tier_boundary_ten():
    assert tiered_discount_rate(10) == 0.15


def test_tier_above_ten():
    assert tiered_discount_rate(20) == 0.15


# ---------- calculate_tax ----------

def test_tax_basic():
    assert calculate_tax(100, 0.15) == 15.0


# ---------- format_currency ----------

def test_format_currency_small():
    assert format_currency(99.9) == "$99.90"


def test_format_currency_thousands():
    assert format_currency(1234.5) == "$1,234.50"


def test_format_currency_millions():
    assert format_currency(1000000) == "$1,000,000.00"


# ---------- calculate_total ----------

def test_total_no_discount():
    # 2 units, no discount tier, 15% tax
    # subtotal = 20, no discount, tax = 3, total = 23
    assert calculate_total(10, 2, 0.15) == 23.0


def test_total_with_discount():
    # 10 units at $10, 15% quantity discount, 15% tax
    # subtotal = 100, after discount = 85, tax = 12.75, total = 97.75
    assert calculate_total(10, 10, 0.15) == 97.75
